package com.mahallat.generatedenteties;
// Generated Aug 13, 2018 2:54:44 AM by Hibernate Tools 5.1.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gallery generated by hbm2java
 */
@Entity
@Table(name = "gallery", catalog = "mahallat")
public class Gallery implements java.io.Serializable {

	private int id;
	private String gallerycol;

	public Gallery() {
	}

	public Gallery(int id) {
		this.id = id;
	}

	public Gallery(int id, String gallerycol) {
		this.id = id;
		this.gallerycol = gallerycol;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "gallerycol", length = 45)
	public String getGallerycol() {
		return this.gallerycol;
	}

	public void setGallerycol(String gallerycol) {
		this.gallerycol = gallerycol;
	}

}
