package com.mahallat.generatedenteties;
// Generated Aug 13, 2018 2:54:44 AM by Hibernate Tools 5.1.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Offers generated by hbm2java
 */
@Entity
@Table(name = "offers", catalog = "mahallat")
public class Offers implements java.io.Serializable {

	private int id;
	private Product product;
	private String price;

	public Offers() {
	}

	public Offers(int id) {
		this.id = id;
	}

	public Offers(int id, Product product, String price) {
		this.id = id;
		this.product = product;
		this.price = price;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "price", length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

}
