package com.mahallat.generatedenteties;
// Generated Aug 13, 2018 2:54:44 AM by Hibernate Tools 5.1.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "mahallat")
public class Product implements java.io.Serializable {

	private Integer id;
	private Store store;
	private String name;
	private String active;
	private String createdAt;
	private String updatedAt;
	private String image;
	private String price;
	private String description;
	private Set<Offers> offerses = new HashSet<Offers>(0);
	private Set<ProductRating> productRatings = new HashSet<ProductRating>(0);
	private Set<ProductLike> productLikes = new HashSet<ProductLike>(0);

	public Product() {
	}

	public Product(Store store, String name, String active, String createdAt, String updatedAt, String image,
			String price, String description, Set<Offers> offerses, Set<ProductRating> productRatings,
			Set<ProductLike> productLikes) {
		this.store = store;
		this.name = name;
		this.active = active;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.image = image;
		this.price = price;
		this.description = description;
		this.offerses = offerses;
		this.productRatings = productRatings;
		this.productLikes = productLikes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "active", length = 45)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "created_at", length = 45)
	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_at", length = 45)
	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Column(name = "price", length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Offers> getOfferses() {
		return this.offerses;
	}

	public void setOfferses(Set<Offers> offerses) {
		this.offerses = offerses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductRating> getProductRatings() {
		return this.productRatings;
	}

	public void setProductRatings(Set<ProductRating> productRatings) {
		this.productRatings = productRatings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProductLike> getProductLikes() {
		return this.productLikes;
	}

	public void setProductLikes(Set<ProductLike> productLikes) {
		this.productLikes = productLikes;
	}

}
