package com.mahallat.generatedenteties;
// Generated Aug 13, 2018 2:54:44 AM by Hibernate Tools 5.1.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Store generated by hbm2java
 */
@Entity
@Table(name = "store", catalog = "mahallat")
public class Store implements java.io.Serializable {

	private Integer id;
	private Category category;
	private User user;
	private String name;
	private String createdAt;
	private String updatedAt;
	private String active;
	private String description;
	private String longitude;
	private String latitude;
	private String openHour;
	private String closeHour;
	private String image;
	private Set<StoreRating> storeRatings = new HashSet<StoreRating>(0);
	private Set<StoreLike> storeLikes = new HashSet<StoreLike>(0);
	private Set<Product> products = new HashSet<Product>(0);

	public Store() {
	}

	public Store(Category category, User user, String name, String createdAt, String updatedAt, String active,
			String description, String longitude, String latitude, String openHour, String closeHour, String image,
			Set<StoreRating> storeRatings, Set<StoreLike> storeLikes, Set<Product> products) {
		this.category = category;
		this.user = user;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.active = active;
		this.description = description;
		this.longitude = longitude;
		this.latitude = latitude;
		this.openHour = openHour;
		this.closeHour = closeHour;
		this.image = image;
		this.storeRatings = storeRatings;
		this.storeLikes = storeLikes;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "created_at", length = 45)
	public String getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(String createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_at", length = 45)
	public String getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(String updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "active", length = 45)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "longitude", length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "open_hour", length = 45)
	public String getOpenHour() {
		return this.openHour;
	}

	public void setOpenHour(String openHour) {
		this.openHour = openHour;
	}

	@Column(name = "close_hour", length = 45)
	public String getCloseHour() {
		return this.closeHour;
	}

	public void setCloseHour(String closeHour) {
		this.closeHour = closeHour;
	}

	@Column(name = "image", length = 45)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
	public Set<StoreRating> getStoreRatings() {
		return this.storeRatings;
	}

	public void setStoreRatings(Set<StoreRating> storeRatings) {
		this.storeRatings = storeRatings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
	public Set<StoreLike> getStoreLikes() {
		return this.storeLikes;
	}

	public void setStoreLikes(Set<StoreLike> storeLikes) {
		this.storeLikes = storeLikes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "store")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
